module-name: cloud-manager
rc-tag: 0.1.9
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/cloud-manager:0.1.9
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
