module-name: cloud-manager
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/cloud-manager:main
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - '**/*_test.go'
    - 'pkg/testinfra/**'
