module-name: cloud-manager
rc-tag: v0.1.4
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/cloud-manager:v0.1.4
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
