module-name: cloud-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/cloud-manager:v20240311-5cf288e9
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
