# permissions for end users to edit awsnfsvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsnfsvolume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-manager
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: awsnfsvolume-editor-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsnfsvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsnfsvolumes/status
  verbs:
  - get
