# permissions for end users to edit gcpnfsvolumerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gcpnfsvolumerestore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-manager
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: gcpnfsvolumerestore-editor-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpnfsvolumerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpnfsvolumerestores/status
  verbs:
  - get
