# permissions for end users to view nfsinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nfsinstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-manager
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: nfsinstance-viewer-role
rules:
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - nfsinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - nfsinstances/status
  verbs:
  - get
