# permissions for end users to view cloudresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudresources-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-resources-manager
    app.kubernetes.io/part-of: cloud-resources-manager
    app.kubernetes.io/managed-by: kustomize
  name: cloudresources-viewer-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - cloudresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - cloudresources/status
  verbs:
  - get
