---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - ipranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - ipranges/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - ipranges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - nfsinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - nfsinstances/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - nfsinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - scope
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - scope/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - scope/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - vpcpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - vpcpeerings/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - vpcpeerings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsnfsvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsnfsvolumes/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsnfsvolumes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - cloudresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - cloudresources/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - cloudresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpnfsvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpnfsvolumes/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpnfsvolumes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - ipranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - ipranges/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - ipranges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymas/status
  verbs:
  - get
