apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AwsNfsVolume
metadata:
  name: awsnfsvolume-sample
spec:
  ipRange:                         # required
    name: iprange_name
    namespace: iprange_namespace
  capacity: 10G                    # required
  performanceMode: generalPurpose  # generalPurpose or maxIO, defaults to generalPurpose
  throughput: bursting             # bursting or elastic, defaults to bursting
  volume:
    name: pv_name
    labels:
      pv/label: value
    annotations:
      pv/annotation: value
