configMapGenerator:
  - name: awsnfsvolumes-ui.operator.kyma-project.io
    files:
      - details
      - form
      - general
      - list
      - translations
    options:
        disableNameSuffixHash: true
        labels:
          busola.io/extension: resource
          busola.io/extension-version: "0.5"
