
apiDisabled:
  variations:
    enabled: false
    disabled: true
  targeting:
    - name: All APIs are disabled for trial SKR
      query: brokerPlan == "trial"
      variation: disabled
    - name: Disabled APIs on stage and prod
      query: feature in ["nfsBackup", "peering"] and landscape != "dev"
      variation: disabled
  defaultRule:
    variation: enabled
ipRangeAutomaticCidrAllocation:
  variations:
    enabled: false
    disabled: true
  targeting:
    - name: Enabled on dev 059dbc39-fd2b-4186-b0e5-8a1bc8ede5b8
      query: landscape == "dev" and kyma == "059dbc39-fd2b-4186-b0e5-8a1bc8ede5b8"
      variation: enabled
  defaultRule:
    variation: disabled
