apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
spec:
  volumeName: nfs-vol-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: ""
