name: PR Checks
run-name: '${{github.event.pull_request.title}}'
'on':
  - pull_request
env:
  PIPELINE: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Display Go version
        run: go version
      - name: Build and test
        run: |
          ./config/sync.sh
          go mod tidy
          go mod download
          make build
          make test
      - name: Check modified files
        run: git diff --exit-code
