name: PR Checks
run-name: '${{github.event.pull_request.title}}'
'on':
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Display Go version
        run: go version
      - name: Build and test KCP
        working-directory: components/kcp
        run: |
          go mod tidy
          go mod download
          make build
          make test
      - name: Build and test LIB
        working-directory: components/lib
        run: |
          go mod tidy
          go mod download
          go build
          go test
      - name: Check modified files
        run: git diff --exit-code